# Generated by Django 4.2.4 on 2023-10-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_membership_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_remain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
