# Generated by Django 4.2.4 on 2023-10-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_membership_app', '0002_membership_membership_remain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_remain',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
